/* Generated By:JavaCC: Do not edit this line. ParserConstants.java */
public interface ParserConstants {

  int EOF = 0;
  int TOP = 5;
  int UNIT = 6;
  int WITH = 7;
  int RLOLLIPOP = 8;
  int LLOLLIPOP = 9;
  int RARROW = 10;
  int LARROW = 11;
  int LPAREN = 12;
  int RPAREN = 13;
  int LBRACE = 14;
  int RBRACE = 15;
  int LBRACKET = 16;
  int RBRACKET = 17;
  int COLON = 18;
  int COMMA = 19;
  int HAT = 20;
  int FIRST = 21;
  int SECOND = 22;
  int IDENTIFIER = 23;
  int LETTER = 24;
  int DIGIT = 25;
  int OTHER = 26;

  int DEFAULT = 0;

  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "\"<T>\"",
    "\"()\"",
    "\"&\"",
    "\"-o\"",
    "\"o-\"",
    "\"->\"",
    "\"<-\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"[\"",
    "\"]\"",
    "\":\"",
    "\",\"",
    "\"^\"",
    "\"<fst>\"",
    "\"<snd>\"",
    "<IDENTIFIER>",
    "<LETTER>",
    "<DIGIT>",
    "<OTHER>",
  };

}
